version: 2

updates:
- package-ecosystem: "github-actions"
  directory: "/"
  groups:
    # xref: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
    ci:
      patterns:
      - "*"
  schedule:
    interval: "weekly"
    day: "sunday"
  labels:
  - kind/dependency
  - kind/chore
  - kind/skip-release-notes
  - component/github-actions
- package-ecosystem: "gomod"
  directory: "/"
  groups:
    go:
      update-types: [ "minor", "patch" ]
  schedule:
    interval: "weekly"
    day: "sunday"
  labels:
  - kind/dependency
  - kind/chore
- package-ecosystem: "docker"
  directory: "/"
  groups:
    docker:
      update-types: [ "minor", "patch" ]
  schedule:
    interval: "weekly"
    day: "sunday"
  labels:
  - kind/dependency
  - kind/chore
- package-ecosystem: "bundler"
  directory: "/"
  groups:
    ruby:
      update-types: [ "minor", "patch" ]
  schedule:
    interval: "weekly"
    day: "sunday"
  labels:
  - kind/dependency
  - kind/chore
- package-ecosystem: "pip"
  directory: "/"
  groups:
    python:
      update-types: [ "minor", "patch" ]
  schedule:
    interval: "weekly"
    day: "sunday"
  labels:
  - kind/dependency
  - kind/chore
- package-ecosystem: "npm"
  directory: "/"
  groups:
    node:
      update-types: [ "minor", "patch" ]
  schedule:
    interval: "weekly"
    day: "sunday"
  labels:
  - kind/dependency
  - kind/chore
