apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: kustomize-simple
spec:
  schema:
    apiVersion: v1alpha1
    kind: KustomizeSimple
    spec:
      prefix: string | default="kustomize-simple"
  resources:
    - id: resourceKustomization
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Resource
        metadata:
          name: "${schema.spec.prefix}-resource-name"
        spec:
          componentRef:
            name: kustomize-simple-component
          resource:
            byReference:
              resource:
                name: kustomize-resource
          interval: 10m
    - id: gitrepository
      template:
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: GitRepository
        metadata:
          name: podinfo
          namespace: default
        spec:
          interval: 5m
          url: ${resourceKustomization.status.resource.access.?repoUrl}
          ref:
            commit: ${resourceKustomization.status.resource.access.?commit}
    - id: kustomization
      template:
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: "${schema.spec.prefix}-kustomization-name"
        spec:
          targetNamespace: default
          interval: 1m
          prune: true
          sourceRef:
            kind: GitRepository
            name: ${gitrepository.metadata.name}
          path: "kustomize"
          patches:
            # e2e-test related patch to validate deployment
            - patch: |
                - op: replace
                  path: /metadata/name
                  value: kustomize-simple-podinfo
                - op: add
                  path: /spec/template/metadata/labels/app.kubernetes.io~1name
                  value: kustomize-simple-podinfo
              target:
                kind: Deployment
                name: .*
            - patch: |
                - op: replace
                  path: /spec/minReplicas
                  value: 1
                - op: replace
                  path: /spec/maxReplicas
                  value: 1
              target:
                kind: HorizontalPodAutoscaler
                name: .*
