name: Latest

on:
  workflow_run:
    workflows: [ "Kubernetes Controller" ]        # name of the workflow that must complete
    types:
      - completed

permissions:
  contents: read

jobs:
  publish-controller:
    name: Controller Image
    if: ${{
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == github.event.repository.default_branch &&
      github.event.workflow.name == 'Kubernetes Controller' }}
    runs-on: large_runner
    permissions:
      checks: write
      contents: read
      packages: write
    steps:
      - uses: LouisBrunner/checks-action@v2.0.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Publish Latest Controller Image"
          status: in_progress
          sha: ${{ github.event.workflow_run.head_sha }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          sparse-checkout: |
            kubernetes/controller
            .github/workflows/kubernetes-controller.yml
            Taskfile.yml
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Multi-Arch
        id: build_push
        run: task kubernetes/controller:docker-build/multi-arch PUSH=true

      - uses: LouisBrunner/checks-action@v2.0.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Publish Latest Controller Image"
          conclusion: ${{ job.status }}
          status: 'completed'
          output: |
            {"summary":"${{ steps.build_push.outputs.summary }}"}
          sha: ${{ github.event.workflow_run.head_sha }}
