name: Renovate OCM
on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight UTC
  workflow_dispatch:
    inputs:
      repoCache:
        description: 'Reset or disable the cache?'
        type: choice
        default: enabled
        options: [ enabled, disabled, reset ]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - .github/renovate.json5
      - .github/workflows/renovate.yml

env:
  cache_archive: renovate_cache.tar.gz
  cache_dir: /tmp/renovate/cache/renovate/repository
  cache_key: renovate-cache
  RENOVATE_CONFIG_FILE: .github/renovate.json5

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          sparse-checkout:
            ${{ env.RENOVATE_CONFIG_FILE }}

      # Restore previous cache artifact if enabled
      - name: Restore renovate cache artifact
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.repoCache != 'disabled' }}
        uses: dawidd6/action-download-artifact@ac66b43f0e6a346234dd65d4d0c8fbb31cb316e5 # v11
        continue-on-error: true
        with:
          name: ${{ env.cache_key }}
          path: cache-download

      - name: Extract renovate cache
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.repoCache != 'disabled' }}
        run: |
          set -euxo pipefail
          if [ ! -d cache-download ]; then
            echo "No cache found."
            exit 0
          fi
          mkdir -p "$cache_dir"
          tar -xzf "cache-download/${cache_archive}" -C "$cache_dir"
          sudo chown -R 12021:0 /tmp/renovate/
          ls -R "$cache_dir" || true

      - if: ${{ github.event_name != 'pull_request' && github.repository_owner == 'open-component-model' }}
        id: generate_token
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
        with:
          app-id: ${{ secrets.OCMBOT_APP_ID }}
          private-key: ${{ secrets.OCMBOT_PRIV_KEY }}

      - name: Ensure Dry-Run on Pull Requests
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "RENOVATE_DRY_RUN=extract" >> $GITHUB_ENV

      - name: Run
        uses: renovatebot/github-action@7876d7a812254599d262d62b6b2c2706018258a2 # v43.0.10
        with:
          env-regex: |
            ^(?:RENOVATE_\w+|LOG_LEVEL|GITHUB_COM_TOKEN|GONOPROXY|GOPRIVATE|NODE_OPTIONS|(?:HTTPS?|NO)_PROXY|(?:https?|no)_proxy)$
          token: ${{ steps.generate_token.outputs.token || secrets.GITHUB_TOKEN }}
        env:
          GONOPROXY: 'ocm.software/open-component-model/*'
          GOPRIVATE: 'ocm.software/open-component-model/*'
          RENOVATE_ONBOARDING: 'false'
          RENOVATE_USERNAME: 'ocmbot[bot]'
          RENOVATE_PLATFORM: 'github'
          RENOVATE_PLATFORM_COMMIT: 'true'
          RENOVATE_REPOSITORIES: "${{ github.repository }}"
          RENOVATE_REPOSITORY_CACHE: ${{ github.event_name == 'workflow_dispatch' && inputs.repoCache || 'enabled' }}
          RENOVATE_ALLOWED_ENV: 'GONOPROXY,GOPRIVATE'
          RENOVATE_ALLOWED_COMMANDS: |
            ^(command -v go >/dev/null 2>&1 \|\| exit 0;\s*)?find\s+\.\s+-name\s+\"go\.mod\".*-path\s+'\*/integration/\*'.*go\s+mod\s+tidy

      - name: Compress renovate cache
        if: ${{ env.RENOVATE_DRY_RUN == '' && (github.event_name != 'workflow_dispatch' || inputs.repoCache != 'disabled') }}
        run: |
          set -euxo pipefail
          ls "$cache_dir" || true
          tar -czvf "$cache_archive" -C "$cache_dir" .

      - name: Upload renovate cache artifact
        if: ${{ env.RENOVATE_DRY_RUN == '' && (github.event_name != 'workflow_dispatch' || inputs.repoCache != 'disabled') }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ env.cache_key }}
          path: ${{ env.cache_archive }}
          retention-days: 1
